음악 검색 및 재생 라이브러리 연동
boostcampwm-2022/iOS05-Segno pull request #155
Opened 2022-12-05 14:39 UTC by radiantchoi

12/1~12/5 #141 #142 #147 #148 #149

## 작업한 내용
### 음악 검색을 위한 샤잠킷을 연동했습니다.
- 일단 작성 뷰 컨트롤러에 붙어 있습니다.
### 음악 재생을 위한 뮤직킷을 연동했습니다.
- 마찬가지로 일단 일기 상세 뷰 컨트롤러에 붙여 두었습니다.

## 고민한 점 및 어려웠던 점
### 샤잠킷의 결과에 따라 처리하는 것에 대해 고민했습니다.
- 검색 성공, 검색 실패뿐만 아니라 검색 중단에 대해서도 고려해야 했기 때문에, 이 경우 어떤 이벤트를 보내야 할지 고민했습니다.
- 구조에 대해 더 생각해보고 리팩토링할 때 해결할 예정입니다. 많은 조언 부탁드립니다.
### 피드백 결과로, 음원을 찾았을 때 앨범 아트를 어디에 표시해줄지 고민했습니다.
- 지금 생각으로는 검색 버튼의 이미지를 바꾸는 방식으로 하면 좋지 않을까 생각합니다.

2022-12-05 17:25 UTC, LEEYOONJONG commented on Segno/Segno/Data/Session/LoginSession.swift
>              return jwtData[1]
요 부분 더이상 사용하지 않는 부분이니 삭제해도 좋을 것 같습니다

2022-12-05 17:28 UTC, LEEYOONJONG commented on Segno/Segno/Data/Session/LoginSession.swift
>              return jwtData[1]
수정된 코드에선 `segments[1]` 만을 디코딩하는데 사용하네요? 저랑 태호님이 만나서 테스트했을 땐 두번째 요소만 디코딩하면 결과가 때떄로 이상하게 나와 count에 따른 케이스 분류를 해줬는데, 변경된 코드가 원활히 동작하는지 계속 지켜봐야 할 것 같습니다

2022-12-06 01:56 UTC, LEEYOONJONG requested changes
고생하셨습니다!! parseBodyFromJWTData 함수만 삭제 부탁드리겟습니다!!

2022-12-06 02:23 UTC, rudah7 approved these changes
해야할 일들이 많군요 ㅠㅠ
전반적으로 코드 이해를 해봐야할 것 같습니다..!

수고하셨습니다!

2022-12-06 02:23 UTC, rudah7 commented on Segno/Segno/Entity/DiaryDetail.swift
> +#if DEBUG
지난번에 고민했던 것이 반영되었군요! 좋습니다 :)

2022-12-06 02:34 UTC, radiantchoi commented on Segno/Segno/Data/Session/ShazamSession.swift
> +        @unknown default:
그냥 default랑 동작은 같습니다!! 알려지지 않은 경우에 대비하는 default라고 합니다. 애플이 만든 프레임워크다 보니까 패치하고 나면 어떻게 기능이 추가될지 모르는 거고, 그런 경우에 @unknown을 사용해 주면 나중에 switch문이 exhaustive하지 않을 때 노란 줄 에러로 알려 준다고 하네요.

2022-12-06 04:38 UTC, LEEYOONJONG approved these changes
고생하셨씁니다!!!

2022-12-06 04:42 UTC, merged